version: "3.7"

services:
  app:
    build:
      context: ./app
    restart: on-failure
    container_name: service-application
    ports:
      - "8080:8080"
    depends_on:
      - "mongo"
    env_file: ./.env
    volumes: 
      - ./logs:/logs
    networks:
      - app-internal-network

  mongo:
    image: mongo:latest
    restart: always
    networks:
      - app-internal-network
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    volumes:
      - ./database:/data/db

  mongo_express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - "mongo"
    networks:
      - app-internal-network
    env_file: ./.env
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASS}

networks:
  app-internal-network:
    driver: bridge
